<a href="https://colab.research.google.com/github/Daylight0079/AuthTest/blob/master/Learn_R_Syntax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### R 타입

In [ ]:
# Vector type
num <- c(1, 2, 3)
cat <- c("apple", "banana", "cherry")

[1] 1 2 3


In [ ]:
print(num)
print(num*num)
print(num+num)

[1] 1 2 3
[1] 1 4 9
[1] 2 4 6


In [ ]:
# Matrix type
mat <- matrix(1:9, nrow=3, ncol=3)

In [ ]:
print(mat)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


In [ ]:
print(mat[1,])

[1] 1 4 7


In [ ]:
print(mat[,2])

[1] 4 5 6


In [ ]:
print(mat[3,3])

[1] 9


In [ ]:
# Array type
a <- array(1:8, dim = c(2, 2, 2))

In [ ]:
print(a)

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8



In [ ]:
print(a[1,,])

     [,1] [,2]
[1,]    1    5
[2,]    3    7


In [ ]:
# List 타입
l <- list(name="Alice", age=25, scores=c(90, 80, 85))

In [ ]:
print(l[1])

$name
[1] "Alice"



In [ ]:
print(l$name)

[1] "Alice"


In [ ]:
print(l$scores[2])

[1] 80


In [ ]:
# Factor 타입
gender <- factor(c("male", "female", "male"))

In [ ]:
print(gender[1])

[1] male
Levels: female male


In [ ]:
x <- 10
y <- x + 10

In [ ]:
print(x)
print(y)

[1] 10
[1] 20


In [ ]:
d <- data.frame(name = c("Alice", "Bob", "Charlie"), age = c(25, 30, 35))
print(d$name)

[1] "Alice"   "Bob"     "Charlie"


In [ ]:
print(d[1])

     name
1   Alice
2     Bob
3 Charlie


In [ ]:
print(d$name)

[1] "Alice"   "Bob"     "Charlie"


In [ ]:
print(d$name[1])

[1] "Alice"


## NULL 사용 예제

NULL은 주로 객체가 존재하지 않음을 나타낼 때 사용. is.null 함수 사용 가능

In [ ]:
# 리스트 생성
my_list <- list(a = 1, b = 2, c = 3)
print(my_list)

$a
[1] 1

$b
[1] 2

$c
[1] 3



In [ ]:
# 'b' 요소 제거
my_list$b <- NULL
print(my_list)

$a
[1] 1

$c
[1] 3



In [ ]:
# NULL 객체 검사
x <- NULL
is.null(x)

[1] TRUE

## NA 사용 예제

값이 존재하지 않음을 나타냄. is.na 함수를 사용할 수 있음

In [ ]:
# 데이터 프레임 생성
my_data <- data.frame(name = c("Alice", "Bob", "Charlie"),
                      age = c(25, NA, 35))

# NA 값 찾기
missing_age <- is.na(my_data$age)

# 결측값이 있는 행 출력
print(missing_age)
print(my_data$age[missing_age])

[1] FALSE  TRUE FALSE
[1] NA


## 함수 생성과 사용

In [ ]:
# 사용자 정의 함수 생성
check_average <- function(numbers, threshold) {
  avg <- mean(numbers, na.rm = TRUE)  # NA 값을 제외하고 평균 계산
  return(avg > threshold)  # 평균이 임계값보다 높은지 여부를 반환
}

In [ ]:
# 함수 사용 예
numbers <- c(1, 2, 3, 4, 5, NA)
threshold <- 3
result <- check_average(numbers, threshold)

# 결과 출력
print(result)


[1] FALSE


## 표준화

In [ ]:
# 표준화 예제
data <- c(1, 2, 3, 4, 5)

# 표준화
standardized_data <- scale(data)

In [ ]:
standardized_data

[,1]      
[1,] -1.2649111
[2,] -0.6324555
[3,]  0.0000000
[4,]  0.6324555
[5,]  1.2649111

## Data Frame

In [ ]:
d = read.csv("https://s3-geospatial.s3-us-west-2.amazonaws.com/train.csv")

In [ ]:
head(d)

PassengerId Survived Pclass
1 1           0        3     
2 2           1        1     
3 3           1        3     
4 4           1        1     
5 5           0        3     
6 6           0        3     
  Name                                                Sex    Age SibSp Parch
1 Braund, Mr. Owen Harris                             male   22  1     0    
2 Cumings, Mrs. John Bradley (Florence Briggs Thayer) female 38  1     0    
3 Heikkinen, Miss. Laina                              female 26  0     0    
4 Futrelle, Mrs. Jacques Heath (Lily May Peel)        female 35  1     0    
5 Allen, Mr. William Henry                            male   35  0     0    
6 Moran, Mr. James                                    male   NA  0     0    
  Ticket           Fare    Cabin Embarked
1 A/5 21171         7.2500       S       
2 PC 17599         71.2833 C85   C       
3 STON/O2. 3101282  7.9250       S       
4 113803           53.1000 C123  S       
5 373450            8.0500       S       
6 330877            8.4583       Q

In [ ]:
summary(d)

  PassengerId       Survived          Pclass          Name          
 Min.   :  1.0   Min.   :0.0000   Min.   :1.000   Length:891        
 1st Qu.:223.5   1st Qu.:0.0000   1st Qu.:2.000   Class :character  
 Median :446.0   Median :0.0000   Median :3.000   Mode  :character  
 Mean   :446.0   Mean   :0.3838   Mean   :2.309                     
 3rd Qu.:668.5   3rd Qu.:1.0000   3rd Qu.:3.000                     
 Max.   :891.0   Max.   :1.0000   Max.   :3.000                     
     Sex                 Age            SibSp           Parch       
 Length:891         Min.   : 0.42   Min.   :0.000   Min.   :0.0000  
 Class :character   1st Qu.:22.00   1st Qu.:0.000   1st Qu.:0.0000  
 Mode  :character   Median :29.70   Median :0.000   Median :0.0000  
                    Mean   :29.70   Mean   :0.523   Mean   :0.3816  
                    3rd Qu.:35.00   3rd Qu.:1.000   3rd Qu.:0.0000  
                    Max.   :80.00   Max.   :8.000   Max.   :6.0000  
    Ticket               Fare     

In [ ]:
str(d)

'data.frame':	891 obs. of  12 variables:
 $ PassengerId: int  1 2 3 4 5 6 7 8 9 10 ...
 $ Survived   : int  0 1 1 1 0 0 0 0 1 1 ...
 $ Pclass     : int  3 1 3 1 3 3 1 3 3 2 ...
 $ Name       : chr  "Braund, Mr. Owen Harris" "Cumings, Mrs. John Bradley (Florence Briggs Thayer)" "Heikkinen, Miss. Laina" "Futrelle, Mrs. Jacques Heath (Lily May Peel)" ...
 $ Sex        : chr  "male" "female" "female" "female" ...
 $ Age        : num  22 38 26 35 35 ...
 $ SibSp      : int  1 1 0 1 0 0 0 3 0 1 ...
 $ Parch      : int  0 0 0 0 0 0 0 1 2 0 ...
 $ Ticket     : chr  "A/5 21171" "PC 17599" "STON/O2. 3101282" "113803" ...
 $ Fare       : num  7.25 71.28 7.92 53.1 8.05 ...
 $ Cabin      : chr  "" "C85" "" "C123" ...
 $ Embarked   : chr  "S" "C" "S" "S" ...


In [ ]:
print(d$Pclass[1])

[1] 3


In [ ]:
# %>% 문법 이해하기 - 생존자 평균 나이 구해보기
library(dplyr)

In [ ]:
survived_age <- d %>% filter(Survived == 1) %>% summarize(AverageAge = mean(Age, na.rm = TRUE))

In [ ]:
print(survived_age)

  AverageAge
1   28.34369


In [ ]:
non_survived_age <- d %>% filter(Survived == 0) %>% summarize(AverageAge = mean(Age, na.rm = TRUE))

In [ ]:
print(non_survived_age)

  AverageAge
1   30.62618


In [ ]:
non_survived_age = summarize(filter(d, Survived == 0), AverageAge = mean(Age, na.rm = TRUE))

In [ ]:
print(non_survived_age)

  AverageAge
1   30.62618


In [ ]:
sum(is.na(d$Age))

[1] 177

In [ ]:
d$Age <- ifelse(is.na(d$Age), mean(d$Age, na.rm = TRUE), d$Age)

In [ ]:
sum(is.na(d$Age))

[1] 0